repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
        types: [file, python]
      - id: end-of-file-fixer
        types: [file, python]
      - id: check-yaml

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length, "120"]
        types: [file, python]

  # python import sorting
  -   repo: https://github.com/asottile/reorder-python-imports
      rev: v3.10.0
      hooks:
      -   id: reorder-python-imports

  # # yaml formatting
  # -   repo: https://github.com/pre-commit/mirrors-prettier
  #     rev: v3.0.0  # Use the sha / tag you want to point at
  #     hooks:
  #     -   id: prettier
  #         types: [yaml]

  # python code analysis
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=120, --max-complexity=18, --select=B,C,E,F,W,T4,B9 --ignore=E203,E266,E501,E503,W503,F403,E231,B950,C901,B008,B007]
        types: [file, python]

  # python linting
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        args: [--exit-zero]
        entry: pylint --score=no
        language: system
        types: [python]

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML]
        types: [python]